### ISSUE TITLE
Add card options to isValid

### ISSUE THREAD

**Issue by diogomqbm** [ContaAzul/creditcard.js#129]
**Want to request a feature or report a bug?**
I'd like to request a feature to add an options parameter to `isValid` function where it will be possible to specify which cards I'd like to verify. This comes in handy when my payment gateway doesn't support all [supported cards](https://github.com/ContaAzul/creditcard.js#suportted-credit-card-types) and I just want to check with those that work for me. Does that make sense? Is it possible?

**What is the current behavior?**
```js
isValid('4916108926268679'); // returns true
```

**What is the expected behavior?**
```js
isValid('4916108926268679', { cards: ['visa', 'mastercard'] }) // returns true

isValid('4916108926268679', { cards: ['mastercard'] }) // returns false
```

**Comment by cirocfc** [comment]
Hi @diogomqbm ! Thanks for the suggestion. It makes perfect sense in my opinion. At the moment I do not have the time to start developing this feature, so feel free to open a Pull Request and I will happily review and release it :)

**Comment by diogomqbm** [comment]
Hi @cirocfc ! Already made the necessary changes and opened the PR. Please review it in your time :)

**Comment by cirocfc** [comment]
@diogomqbm Thank you for your contribution! The new version is available on [npm](https://www.npmjs.com/package/creditcard.js/v/3.0.5)
