### ISSUE TITLE
Version 2.1.7 | Still on NPM but not on Github anymore (with breaking changes)

### ISSUE THREAD

**Issue by patrickgdl** [ContaAzul/creditcard.js#134]
**Want to request a feature or report a bug?**
 Possible bug

**What is the current behavior?**

Version 2.1.7 has breaking changes noted only on version 3.0.0 ([example](https://unpkg.com/creditcard.js@2.1.7/dist/creditcard.js))

**If the current behavior is a bug, provide the steps to reproduce and, if possible, a minimal demonstration of the problem via https://jsfiddle.net or similar (modelo: https://jsfiddle.net/).**

Run `npm install creditcard.js@2.1.7` and try to use the old way (before 3.0.0)

**What is the expected behavior?**

Should work the old not-functional way.

**Which version of creditcard.js and which browser / OS are affected by this issue? This worked on previous versions of creditcard.js?**

Version: 2.1.7

Hey guys,

A question, did we have a problem with version 2.1.7? I had a problem with breaking changes in a project, working only with the new functional way. I saw that this version still in NPM but not in Github anymore. In fact, after version 2.1.6 I realized that there were indeed breaking changes with version 3.0.0, so version before that should work the old way, right?

Just to really have this information and pass the care to possible uses with the version that is still there in the NPM.

**Comment by cirocfc** [comment]
Hey @patrickgdl 

Yeah, about that. It was a broken version that was automatically and mistakenly published. We tried to remove it from npmjs but according to their policies one cannot remove a published package if it has dependent packages. In our case, there are 2 other packages on npmjs that rely on our package in version 2 (one is outdated and another is private), so unfortunately we could not unpublish this version.

The least damage for now is a deprecated warning made on version 2.1.7, so when checking the version list it is hidden, and when installing version 2 of the library it shows a deprecation warning. 

Sorry about the troubles 😞
