### ISSUE TITLE
Sugestões de melhoria

### ISSUE THREAD

**Issue by pedrofurst** [ContaAzul/creditcard.js#15]
* Sugestão 1: 

As funções que tem o retorno boolean, poderiam começar com `is`.
Exemplo: Ao invez de ser _validate_ poderia ser _**isValid**_ .

 
* Sugestão 2: 

Na descrição dos métodos que são funções na verdade, está assim:
![image](https://cloud.githubusercontent.com/assets/4452152/12846566/5bdb11ce-cbf4-11e5-98fe-dfd99a948ff1.png)

Pensei na seguinte melhoria: 

1. Alterar _Methods_ pra **_Functions_**.

2. Na coluna `Name` colocar só o nome da função e não `obj.Nome`.

3. Alterar o nome da coluna _Description_ pra **_Returns_** e colocar só o retorno. Está repetindo '_Returns  a_ '.

Exemplo: 

Name: **_isValid_**
Returns: **_Boolean_** 

Acho que fica mais objetivo na minha opinião.

 
* Sugestão 3: 
no git está assim:
![image](https://cloud.githubusercontent.com/assets/4452152/12846850/1c223ce0-cbf6-11e5-9e1b-84c176209c51.png)

no site assim: 
![image](https://cloud.githubusercontent.com/assets/4452152/12846865/2fca977e-cbf6-11e5-80fa-37211ae2b9f1.png)

Suporta IE 9+ e safari 8+?

**Comment by fernahh** [comment]
@pedrofurst 

Sobre os nomes dos métodos, gosto da tua sugestão, assim como as melhorias na tabela do site. Teríamos que alterar aqui no README também. Você abre um PR com isso? :smiley: 

Sobre o browser support, faltou o caractere de checked, temos que corrigir.

**Comment by pedrofurst** [comment]
@fernahh  sim, sem problemas..

**Comment by fernahh** [comment]
Valeu @pedrofurst! :punch:
