### ISSUE TITLE
Installation with npm fails

### ISSUE THREAD

**Issue by dtillner** [ContaAzul/creditcard.js#159]
With version 3.0.26 installation with npm fails with error "yarn not found". 

Probably this is because of this line in `package.json`

```json
"preinstall": "yarn dlx only-allow yarn",
```

I can't see why it should be necessary to limit this package to yarn.

Please remove this limitation.

**Comment by cirocfc** [comment]
Sorry about that guys... I accidentally added the same config for our internal packages that rely and only run on yarn when updating this project to yarn 3. Hope latest version ships ok.
