### ISSUE TITLE
Expiration check fails

### ISSUE THREAD

**Issue by jdforsythe** [ContaAzul/creditcard.js#34]
There are two issues with expiration date checking.

First is the line:

    if (yearLength < 2 && yearLength > 4) return false;

`yearLength` can't be both less than 2 and greater than 4.

Second is the line:

    return !(y < 1000 || y >= 3000);

This fails on two-digit expiration years, which are less than 1000.

**Comment by jdforsythe** [comment]
It appears that the first line is not present in the current repo when I forked it, but is in the bower package.

**Comment by fernahh** [comment]
This problem got fixed on v2.0.3, but I not created a Github release. I did it now. It will soon be in the Bower.
