### ISSUE TITLE
Automatically update release with npm script

### ISSUE THREAD

**Issue by matheuspoleza** [ContaAzul/creditcard.js#36]
We're make changes and not updating releases in npm and bower. How we can work with that?

There is a problem that was commented in https://github.com/ContaAzul/creditcard.js/issues/34.

How we can solve that?

## Tasks:

Automatically update release in:

- [ ] NPM
- [ ] Bower
- [ ] Github release

**Comment by fernahh** [comment]
I published last version (v2.0.3) in NPM but no created release on Github.

The bower package is updated based on release version. Now, I created this. But, I believe that we need automate this with NPM Scripts.

**Comment by matheuspoleza** [comment]
Yeah, I think it's necessary to not depending on manual update.

**Comment by matheuspoleza** [comment]
@fernahh but how we can work with branchs? We are always commit to master. Its a good practice? Or is good to have a dev branch or something like that?

**Comment by fernahh** [comment]
Other branch only if the feature break the API. IMHO.

**Comment by felipeuntill** [comment]
Every project have bugs, and not all fixes needs to be released immediately, before talk about automate releases you should describe the release terms.
