### ISSUE TITLE
Credit card validation

### ISSUE THREAD

**Issue by fcpauldiaz** [ContaAzul/creditcard.js#50]
Does the credit card security code validation is only based on length or does it has a math background?

**Comment by fernahh** [comment]
@fcpauldiaz the security code is based on length and a regex to validate type of chars.

```javascript
  isSecurityCodeValid(number, code) {
    let brand = this.getCreditCardNameByNumber(number);
    let numberLength;

    numberLength = (brand === 'Amex') ? 4 : 3;
    let regex = new RegExp(`^[0-9]{${numberLength}}$`);

    return regex.test(code);
}
```

> [Reference](https://github.com/ContaAzul/creditcard.js/blob/master/src/creditCard.js#L36).
