### ISSUE TITLE
Add dist files to be created on post install hook

### ISSUE THREAD

**Issue by fernahh** [ContaAzul/creditcard.js#62]
Today there is a folder [dist](https://github.com/ContaAzul/creditcard.js/tree/master/dist) that should be commited. :hankey: 

### Tasks

- [x] Add post install hook to generate dist files

**Comment by carlosrberto** [comment]
Why not just ignore the `dist` folder and generate it before `npm publish`?
Another option may be generate directly on travis. I did this in a recent project.
