### ISSUE TITLE
Replace phantomjs by a stable tool

### ISSUE THREAD

**Issue by fernahh** [ContaAzul/creditcard.js#65]

**Comment by edmolima** [comment]
Você pode explanar mais sobre qual sua idéia ao querer mudar phantomjs? Pode dar um overview melhor?

**Comment by fernahh** [comment]
@edmolima os principais pontos são:

1. O Phanthom foi descontinuado;
2. É pesado;
3. Existem ferramentas melhores e mais leves (como o Jest).

**Comment by edmolima** [comment]
Ok @fernahh trabalharei nisso, eu realmente tinha esses pontos como problemas a phantomjs e como você o usa aqui. Vou ver o que posso fazer.

**Comment by carlosrberto** [comment]
@edmolima @fernahh alguém já começou a trabalhar nessa issue?
Se quiserem me disponho a fazer a atualização para o Jest.

**Comment by fernahh** [comment]
@carlosrberto acredito que não. Acho que tu pode pegar :smile:

**Comment by carlosrberto** [comment]
Combinado @fernahh.
Entre hoje e amanhã começo a trabalhar nisso!

**Comment by carlosrberto** [comment]
@fernahh só uma dúvida. Isso deve ser feito em uma branch a partir da `master` ou a partir da branch `v3` ?

**Comment by fernahh** [comment]
@carlosrberto a partir da `v3`.
