### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by fernahh** [ContaAzul/creditcard.js#66]

**Comment by edmolima** [comment]
@fernahh o que você pretende com adicionar prettier? Vocês tem um ``eslintrc.json`` pode ser usado com prettier plugin na maioria dos editores como diz na sua documentação: [Prettier Integration Eslint](https://prettier.io/docs/en/eslint.html)

Deixe-me saber mais sobre o assunto.

**Comment by fernahh** [comment]
@edmolima sugeri o prettier por não precisar de muita configuração, mas podemos manter essas configurações do eslint. 

ou também dá pra apenas habilitar a opção de `--fix` no eslint, já resolveria problemas com formatação.

**Comment by carlosrberto** [comment]
Costumo utilizar essa lib para disparar o `eslint` antes de um `commit` ou `push`, se não passar o commit ou push é cancelado.

https://github.com/typicode/husky

**Comment by fernahh** [comment]
@carlosrberto acho uma ótima ideia!
