### ISSUE TITLE
JCB Cards

### ISSUE THREAD

**Issue by lokharth** [ContaAzul/creditcard.js#84]
Can we get support for JCB Cards ?

Thanks :D

**Comment by randalmaia** [comment]
Hello @lokharth, thank you for your issue.
Do you have more information about JCB cards scheme?

**Comment by lokharth** [comment]
Sure,
The regex I usually use to identify JCB cards is this one:

^(?:2131|1800|35[0-9]{3})[0-9]{11}$

**Comment by dedicio** [comment]
HI @lokharth 

Thanks for contribution!

This improvement was implemented in PR #120 

See more details: https://contaazul.github.io/creditcard.js/
