### ISSUE TITLE
Incorrect: isValid(1231233212) return true

### ISSUE THREAD

**Issue by adrianoresende** [ContaAzul/creditcard.js#85]
Why this number`isValid('1231233212')` is returning `true` ?

**Comment by randalmaia** [comment]
Hello @adrianoresende thank you for your issue.

creditcard.js is using [Luhn Algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm) to validate the creditcard numbers. 

This card number ```1231233212``` is valid and belongs to [UATP](https://en.wikipedia.org/wiki/Universal_Air_Travel_Plan)
You can check the card numbers patterns,ranges and owners [here](https://en.wikipedia.org/wiki/Payment_card_number#Major_Industry_Identifier_.28MII.29)
