### ISSUE TITLE
Expired cc dates return as valid

### ISSUE THREAD

**Issue by paulogr** [ContaAzul/creditcard.js#99]
Hello, nice lib, very lightweight.

Should expired dates return as valid?

`cc.isExpirationDateValid(11,2017)` returns true but 2017 is past.

Are you accepting PR's ?

Thanks!

**Comment by dedicio** [comment]
Hi @paulogr!

This issue was fixed on PR #120 

See changes: https://contaazul.github.io/creditcard.js/

Thanks!
